services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: presence-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf # Mount the redis.conf file
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"] # Run Redis with the custom config
    restart: always

volumes:
  redis_data:
    driver: local
